/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Deber;

import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author USER-HP
 */
public class EncontrarVocales extends javax.swing.JFrame {

    /**
     * Creates new form EncontrarVocales
     */
    public EncontrarVocales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTexto = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnVocales = new javax.swing.JButton();
        btnEspacios = new javax.swing.JButton();
        btnSeparar = new javax.swing.JButton();
        btnReversa = new javax.swing.JButton();
        btnRemplazar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("DEBER");

        jLabel2.setText("Igrese un texto");

        btnVocales.setText("VOCALES");
        btnVocales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVocalesActionPerformed(evt);
            }
        });

        btnEspacios.setText("ESPACIOS");
        btnEspacios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEspaciosActionPerformed(evt);
            }
        });

        btnSeparar.setText("SEPARAR");
        btnSeparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSepararActionPerformed(evt);
            }
        });

        btnReversa.setText("REVERSA");
        btnReversa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReversaActionPerformed(evt);
            }
        });

        btnRemplazar.setText("REMPLAZAR");
        btnRemplazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemplazarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEspacios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVocales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnSeparar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btnReversa)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnRemplazar)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVocales)
                    .addComponent(btnSeparar)
                    .addComponent(btnRemplazar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReversa)
                    .addComponent(btnEspacios))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVocalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVocalesActionPerformed

        String cadena = txtTexto.getText();
        this.encontrarVocales(cadena);


    }//GEN-LAST:event_btnVocalesActionPerformed

    private void btnEspaciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEspaciosActionPerformed

        String cadena = txtTexto.getText();
        this.contarEspacios(cadena);


    }//GEN-LAST:event_btnEspaciosActionPerformed

    private void btnSepararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSepararActionPerformed
        // TODO add your handling code here:
        String cadena = txtTexto.getText();
        this.separarPalabras(cadena);

    }//GEN-LAST:event_btnSepararActionPerformed

    private void btnReversaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReversaActionPerformed
        // TODO add your handling code here:
        String cadena = txtTexto.getText();
        this.reversa(cadena);


    }//GEN-LAST:event_btnReversaActionPerformed

    private void btnRemplazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemplazarActionPerformed
        // TODO add your handling code here:
        String cadena = txtTexto.getText();
        this.remplazar(cadena);

    }//GEN-LAST:event_btnRemplazarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EncontrarVocales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EncontrarVocales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EncontrarVocales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EncontrarVocales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EncontrarVocales().setVisible(true);
            }
        });
    }

    public void encontrarVocales(String cadena) {

        int cont_a = 0;
        int cont_e = 0;
        int cont_i = 0;
        int cont_o = 0;
        int cont_u = 0;

        for (int i = 0; i < cadena.length(); i++) {

            switch (cadena.charAt(i)) {
                case 'a', 'A' ->
                    cont_a++;
                case 'e', 'E' ->
                    cont_e++;
                case 'i', 'I' ->
                    cont_i++;
                case 'o', 'O' ->
                    cont_o++;
                case 'u', 'U' ->
                    cont_o++;
                default -> {

                }

            }
        }
        JOptionPane.showMessageDialog(rootPane, "letra a: " + cont_a + "\n"
                + "letra e: " + cont_e + "\n"
                + "letra i: " + cont_i + "\n"
                + "letra o: " + cont_o + "\n"
                + "letra u: " + cont_u);
    }

    public void contarEspacios(String cadena) {
        int cont = 0;

        for (int i = 0; i < cadena.length(); i++) {
            if (cadena.charAt(i) == ' ') {
                cont++;
            } else {
            }
        }
        JOptionPane.showMessageDialog(rootPane, "NUMERO DE ESPACIOS : " + cont);
    }

    public void separarPalabras(String cadena) {
        String[] palabras = cadena.split("\\s+");

        JOptionPane.showMessageDialog(rootPane, palabras);

    }

    public void reversa(String cadena) {
        StringBuilder sb = new StringBuilder(cadena);

        sb.reverse();
        JOptionPane.showMessageDialog(rootPane, "CADENA EN REVERSO: " + "\n" + sb);
    }

    public void remplazar(String cadena) {
        StringBuilder sb = new StringBuilder(cadena);
        String cadenaModificada = cadena.replace('O', '$').replace('o', '$');

        JOptionPane.showMessageDialog(rootPane, "MODIFICADO: " + "\n" + cadenaModificada + "\n" + "ORIGINAL: " + "\n" + cadena);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEspacios;
    private javax.swing.JButton btnRemplazar;
    private javax.swing.JButton btnReversa;
    private javax.swing.JButton btnSeparar;
    private javax.swing.JButton btnVocales;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtTexto;
    // End of variables declaration//GEN-END:variables
}
